<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

use App\Models\Attribute;
use App\Models\Element;

class ElementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        /** @var array Elementos asociados a los Atributos */
        $attributes_elements = [
            "1" => [
                'Arte',
                'Autoayuda',
                'Autobiográficos',
                'Aventuras',
                'Cocina',
                'Comic',
                'Contemporaneo',
                'Científicos',
                'Cuentos',
                'Culto',
                'Deporte',
                'Drama',
                'Economía',
                'Empresa',
                'Ensayo',
                'Erótica',
                'Espiritualidad',
                'Ficción',
                'Filología',
                'Guerra',
                'Humor',
                'Idiomas',
                'Juvenil',
                'Manualidades',
                'Marketing',
                'Medicina',
                'Microrrelatos',
                'Música',
                'Novela',
                'Novela Histórica',
                'Novela negra',
                'Novelas Románticas',
                'Política',
                'Psicología y Pedagogia',
                'Religión ',
                'Salud',
                'Sociedad',
                'Suspense',
                'Técnicos',
                'Viajes',
                'Videojuegos'
            ],
            "2" => [
                'Español',
                'Inglés',
                'Francés',
                'Otros Idiomas'
            ],
            "3" => [
                'Bolsillo',
                'Encuedernación de Lujo',
                'Tapa dura',
                'Tapa Blanda'
            ],
            "4" => [
                'Abstracto',
                'Animal',
                'Autorretrato',
                'Bodegón',
                'Concept',
                'Desnudo',
                'Fantasía',
                'Floral',
                'Futurista',
                'Historia',
                'Marina',
                'Naturaleza',
                'Paisaje',
                'Pasado',
                'Política',
                'Pop',
                'Religioso',
                'Retrato',
                'Urbano',
                'Otras temática'
            ],
            "5" => [
                'Abstracto',
                'Barroco',
                'Bizantino',
                'Clásico',
                'Contemporáneo',
                'Cubismo',
                'Expresionismo',
                'Fauvismo',
                'Figurativo',
                'Flamenco',
                'Futurismo',
                'Geométrico',
                'Gótico',
                'Impresionismo',
                'Luminismo',
                'Manierismo',
                'Medieval',
                'Metafísico',
                'Minimalista',
                'Moderno',
                'Naif',
                'Nuevo',
                'Oriental',
                'Pop Art',
                'Positivismo',
                'Puntillismo',
                'Realismo',
                'Renacentista',
                'Rococo',
                'Románico',
                'Simbólico',
                'Surrealismo',
                'Vintage',
                'Otro Estilo'
            ],
            "6" => [
                'Acrílico',
                'Acuarela',
                'Aerosol',
                'Cera',
                'Collage',
                'Esmalte',
                'Grabado',
                'Graffiti',
                'Laca',
                'Lápiz',
                'Litografía',
                'Óleo',
                'Pigmentos',
                'Pastel',
                'Pintura',
                'Pluma',
                'Resina',
                'Serigrafía',
                'Tempera',
                'Textil',
                'Tinta',
                'Tiza',
                'Vinilo',
                'Tierra',
                'Yeso',
                'Metales',
                'Otras Técnicas'
            ],
            "7" => [
                'Abstracto',
                'Animal',
                'Autorretrato',
                'Bodegón',
                'Concept',
                'Desnudo',
                'Fantasía',
                'Floral',
                'Futurista',
                'Historia',
                'Marina',
                'Naturaleza',
                'Paisaje',
                'Pasado',
                'Política',
                'Pop',
                'Religioso',
                'Retrato',
                'Urbano',
                'Otras temática'
            ],
            "8" => [
                'Exterior',
                'Interior',
                'Iluminación',
                'Pared',
                'Techo',
                'Arquitectonica',
                'Relieve',
                'Suspendida',
            ],
            "9" => [
                'Acero',
                'Acero Corten',
                'Acero Inoxidable',
                'Aluminio',
                'Arcilla',
                'Bronce',
                'Cartón',
                'Cemento',
                'Cristal',
                'Espejo',
                'Hierro',
                'Hojalata',
                'Hueso',
                'Luz',
                'Luz Led',
                'Madera',
                'Mármol',
                'Mosaik',
                'Neón',
                'Papel',
                'Perlas',
                'Piedra',
                'Piel',
                'Plástico',
                'Plexiglás',
                'Resina',
                'Taxidermia',
                'Terracota',
                'Textil',
                'Yeso',
                'Zinc',
                'Oro',
                'Plata',
                'Corcho',
                'Cartón',
                'Fluido',
                'Plasma',
                'Otros Materiales'
            ],
            "10" => [
                'Abstracto',
                'Animal',
                'Autorretrato',
                'Bodegón',
                'Concept',
                'Desnudo',
                'Fantasía',
                'Floral',
                'Futurista',
                'Historia',
                'Marina',
                'Naturaleza',
                'Paisaje',
                'Pasado',
                'Política',
                'Pop',
                'Religioso',
                'Retrato',
                'Urbano',
                'Otras temáticas'
            ],
            "11" => [
                'Abstracto',
                'Barroco',
                'Bizantino',
                'Clásico',
                'Contemporáneo',
                'Cubismo',
                'Expresionismo',
                'Fauvismo',
                'Figurativo',
                'Flamenco',
                'Futurismo',
                'Geométrico',
                'Gótico',
                'Impresionismo',
                'Luminismo',
                'Manierismo',
                'Medieval',
                'Metafísico',
                'Minimalista',
                'Moderno',
                'Naif',
                'Nuevo',
                'Oriental',
                'Otros Tipos de Estilo',
                'Pop Art',
                'Positivismo',
                'Puntillismo',
                'Realismo',
                'Renacentista',
                'Rococo',
                'Románico',
                'Simbólico',
                'Surrealismo',
                'Vintage',
                'Otros Tipos de Estilo'
            ],
            "12" => [
                'Arena',
                'Carboncillo',
                'Fieltro',
                'Grabado',
                'Grafito',
                'Impresión Laser',
                'Lápiz',
                'Lapíz Color',
                'Monotiopia',
                'Otras Técnicas',
                'Pastel',
                'Pluma',
                'Relieve',
                'Serigrafía',
                'Tinta',
                'Tiza'
            ],        
            "13" => [
                'Abstracto',
                'Animal',
                'Autorretrato',
                'Bodegón',
                'Concept',
                'Desnudo',
                'Fantasía',
                'Floral',
                'Futurista',
                'Historia',
                'Marina',
                'Naturaleza',
                'Paisaje',
                'Pasado',
                'Política',
                'Pop',
                'Religioso',
                'Retrato',
                'Urbano',
                'Otras temática'
            ],
            "14" => [
                'Blanco y Negro',
                'Color',
                'Composición Digital',
                'Panorámica',
                'Sepia',
                'Otro Estilo'
            ],
            "15" => [
                'Dígital',
                'Física',
                'Compuesta',
                'Litografía',
                'Clave alta',
                'Clave baja',
                'Derechear el histograma',
                'Fotografía infrarroja',
                'Larga exposición diurna',
                'Agua con efecto seda',
                'Barrido de movimiento',
                'Larga exposición nocturna',
                'Fotografía de estrellas',
                'Fotografiar la Vía Láctea',
                'Lightpainting',
                'Fotografiar estelas de luz',
                'Alta velocidad',
                'Gota de agua',
                'Apertura de diafragma',
                'Bokeh',
                'Hiperfocal',
                'Otras técnicas fotográficas',
                'Zooming',
                'Bracketing u horquillado',
                'HDR',
                'Fotografía de humo',
                'Fondo blanco',
                'Fondo negro',
                'Time lapse',
                'Edición',
                'Desaturado selectivo',
                'Método Brenizer',
                'Fotografía Fine Art',
                'Multiexposición en Photoshop',
                'Efecto Orton',
                'Doble exposición',
                'Efecto Adamski',
                'Otras técnicas fotográficas',
            ]
        ];

        DB::transaction(function () use ($attributes_elements) {
            foreach ($attributes_elements as $attribute_id => $elements) {
                /** @var object almacena informacion del atributo*/
                $att = Attribute::find($attribute_id);
                foreach ($elements as $element) {
                    Element::updateOrCreate(['name' => $element, 'attribute_id' => $att->id], []);
                }
            }
        });
    }
}
